-- 1. Create DEPT table
CREATE TABLE DEPT (
    DNO VARCHAR2(3) CONSTRAINT PK_DEPT PRIMARY KEY,
    DNAME VARCHAR2(10) CONSTRAINT UQ_DNAME UNIQUE,
    CONSTRAINT CK_DNO CHECK (DNO LIKE 'D%')
);

-- 2. Create EMP table
CREATE TABLE EMP (
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    EJOB VARCHAR2(9) DEFAULT 'CLRK',
    MGR_ID NUMBER(4),
    BIRTH_DATE DATE,
    SAL NUMBER(7,2) DEFAULT 20001,
    COMM NUMBER(7,2) DEFAULT 1000,
    DEPTNO VARCHAR2(3),
    PRJ_ID VARCHAR2(9) DEFAULT 'CLRK',
    DATE_OF_JOIN DATE,
    CONSTRAINT PK_EMP PRIMARY KEY (EMPNO),
    CONSTRAINT CK_EJOB CHECK (EJOB IN ('CLRK','MGR','A.MGR','GM','CEO')),
    CONSTRAINT CK_SAL CHECK (SAL > 20000),
    CONSTRAINT CK_BIRTH CHECK (BIRTH_DATE < DATE_OF_JOIN),
    CONSTRAINT CK_PRJID CHECK (PRJ_ID IN ('CLRK','MGR','A.MGR','GM','CEO')),
    CONSTRAINT FK_MGR FOREIGN KEY (MGR_ID) REFERENCES EMP(EMPNO),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPTNO) REFERENCES DEPT(DNO)
);

-- 3. Create PROJECTS table
CREATE TABLE PROJECTS (
    DNO VARCHAR2(3) NOT NULL,
    PRJ_NO VARCHAR2(5) NOT NULL,
    PRJ_NAME VARCHAR2(10),
    PRJ_CREDITS NUMBER(2),
    START_DATE DATE,
    END_DATE DATE,
    CONSTRAINT PK_PROJECTS PRIMARY KEY (DNO, PRJ_NO),
    CONSTRAINT FK_PROJECT_DEPT FOREIGN KEY (DNO) REFERENCES DEPT(DNO),
    CONSTRAINT CK_PRJ_NO CHECK (PRJ_NO LIKE 'P%'),
    CONSTRAINT CK_CREDITS CHECK (PRJ_CREDITS BETWEEN 1 AND 10),
    CONSTRAINT CK_END_DATE CHECK (END_DATE > START_DATE)
);

-- 4. Change PRJ_ID datatype from VARCHAR2(9) to VARCHAR2(5)
ALTER TABLE EMP
MODIFY PRJ_ID VARCHAR2(5);

-- 5. Drop constraint on PRJ_ID
ALTER TABLE EMP
DROP CONSTRAINT CK_PRJID;

-- 6. Add composite foreign key on DEPTNO and PRJ_ID
ALTER TABLE EMP
ADD CONSTRAINT FK_EMP_PROJECT
FOREIGN KEY (DEPTNO, PRJ_ID)
REFERENCES PROJECTS (DNO, PRJ_NO);

-- 7. Add LOCATIONS column to DEPT
ALTER TABLE DEPT
ADD LOCATIONS VARCHAR2(9) DEFAULT 'BNG';

-- 8. Add CHECK constraint on LOCATIONS
ALTER TABLE DEPT
ADD CONSTRAINT CK_LOCATIONS
CHECK (LOCATIONS IN ('BNG','MNG','MUB','HYD','CHN'));
